const assert=require('node:assert/strict'),fs=require('node:fs'),{JSDOM,VirtualConsole}=require('jsdom');
const root=require('node:path').resolve(__dirname,'..')+'/';
const scripts=['privacy','analytics','zenchef'].map(x=>fs.readFileSync(root+'assets/js/'+x+'.js','utf8'));
const html='<html lang="fr"><body><a href="/reserver">Réserver</a><div class="zc-widget-config"></div><iframe hidden data-consent-src="https://www.google.com/maps/embed?x=1"></iframe><iframe hidden data-consent-src="https://widget.holiduhost.com/widget/test"></iframe><div class="embed-consent"><div class="embed-notice">Old</div><iframe hidden data-consent-src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Ftest"></iframe></div></body></html>';
function setup(storage){const dom=new JSDOM(html,{url:'https://legrimaldibylevillage.com/',runScripts:'outside-only',virtualConsole:new VirtualConsole()});const w=dom.window;if(storage)w.localStorage.setItem('lv_privacy_consent_v2',JSON.stringify(storage));scripts.forEach(s=>w.eval(s));return dom;}
function click(w,label){const el=[...w.document.querySelector('.lv-consent').querySelectorAll('button')].find(x=>x.textContent===label&&!x.hidden);assert(el,label);el.click();}
function remote(w){return [...w.document.querySelectorAll('script[src],iframe[src]')].filter(e=>e.getAttribute('src').startsWith('https://'));}
let d=setup(),w=d.window;
assert.equal(remote(w).length,0,'No remote optional requests by default');
click(w,'Tout refuser');assert.equal(remote(w).length,0);assert(!w.lvPrivacy.allowed('analytics'));
w.document.querySelector('a').click();assert.equal(remote(w).length,0,'Booking click requests permission first');assert(!w.document.querySelector('.lv-request').hidden);
click(w,'Autoriser ce service');assert(w.document.querySelector('#zenchef-sdk'));assert.equal(w.lvPrivacy.allowed('analytics'),false);assert.equal(w.document.querySelectorAll('iframe[src]').length,0);d.window.close();
d=setup();w=d.window;click(w,'Personnaliser');w.document.querySelector('input[name=maps]').checked=true;click(w,'Enregistrer mes choix');assert.equal(w.document.querySelectorAll('iframe[src]').length,1);assert.equal(w.document.querySelectorAll('script[data-lv-gtm]').length,0);assert(w.lvPrivacy.allowed('maps'));d.window.close();
d=setup();w=d.window;click(w,'Tout accepter');assert.equal(w.document.querySelectorAll('iframe[src]').length,3);assert.equal(w.document.querySelectorAll('script[data-lv-gtm]').length,1);assert.equal(w.document.querySelector('#zenchef-sdk'),null,'SDK still waits for reservation request');let views=w.dataLayer.filter(x=>x[0]==='event'&&x[1]==='page_view');assert.equal(views.length,1);w.lvPrivacy.open();click(w,'Tout accepter');assert.equal(w.dataLayer.filter(x=>x[0]==='event'&&x[1]==='page_view').length,1);w.document.cookie='_ga=test; path=/';w.lvPrivacy.open();click(w,'Tout refuser');assert.equal(w.document.querySelectorAll('iframe[src]').length,0);assert(w['ga-disable-G-1F6HPCJ4JL']);assert(!w.document.cookie.includes('_ga='));const record=JSON.parse(w.localStorage.getItem('lv_privacy_consent_v2'));assert(Object.values(record.choices).every(v=>v===false));d.window.close();
d=setup(record);w=d.window;assert.equal(remote(w).length,0);assert(w.document.querySelector('.lv-consent').hidden);d.window.close();
d=setup({...record,at:Date.now()-181*86400000,choices:{analytics:true,maps:true,media:true,zenchef:true,holidu:true}});w=d.window;assert.equal(remote(w).length,0);assert(!w.document.querySelector('.lv-consent').hidden);d.window.close();
console.log('PASS: default/refusal, granular consent, booking gate, one page view, withdrawal, persistence, expiry.');
